name: easy_voice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  speech_to_text: ^6.6.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  google_translate: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
